In graduate studies, many students find it difficult to achieve good grades because they do not get much support in higher education courses compared to the support that students receive in schools. We can use machine learning for the student grades prediction task so that instructors can help students prepare for topics where student grades were predicted low.

Universities are very prestigious places to access higher education. But the amount of fees universities charge today never equals the support they give to students. Some students need a lot of attention from instructors because if special attention will not be given to those students who are not getting good grades, it could be detrimental to their emotional state and their career in the long run.

By using machine learning algorithms, we can predict how well the students are going to perform so that we can help the students whose grades are predicted low. Student Grades Prediction is based on the problem of regression in machine learning.

## Student Grades Prediction using Python

We need to predict the grades of a student. Now let’s see how we can use machine learning for the task of student grades prediction using Python. I will start this task by importing the necessary Python libraries and the dataset:

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv")
data.head()    

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

The dataset that I am using for the task of students grade prediction is based on the achievements of the students of the Portuguese schools. In this dataset the G1 represents the grades of the first period, G2 represents the grades of the second period, and G3 represents the final grades. Now let’s prepare the data and let’s see how we can predict the final grades of the students:

In [2]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

C:\Users\SHREE\AppData\Local\Temp/ipykernel_5512/476592969.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))


In the above code, I first selected the necessary columns that we need to train a machine learning model for the task of student grades prediction. Then I declared that the G3 column is our target label and then I split the dataset into 20% testing and 80% training. Now let’s see how to train a linear regression model for the task of student grades prediction:

In [3]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8068119434987682


The linear regression model gave an accuracy of about 80% which is not bad in this task. Now let’s have a look at the predictions made by the students’ grade prediction model:

In [4]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[12.67301427 13.87626018 10.75057869 12.90767173 13.87626018]
 [12.67301427 12.67301427 10.75057869 12.90767173  8.64084562]
 [ 9.76622944 12.15696048 10.75057869 10.6884774   5.94745421]
 ...
 [ 5.94745421 12.15696048 10.73581151 10.6884774  10.6884774 ]
 [14.61118478  7.98380897 10.73581151 12.90767173 12.90767173]
 [12.15696048 14.18883146 10.73581151 12.90767173 12.67301427]] [[[14 13  4  0  0]
  [13 14  3  0  4]
  [10 11  2  0  6]
  [13 13  2  0  2]
  [13 14  3  0  4]]

 [[14 13  4  0  0]
  [14 13  4  0  0]
  [10 11  2  0  6]
  [13 13  2  0  2]
  [10  9  2  0  4]]

 [[12 10  2  0  2]
  [12 12  1  0  8]
  [10 11  2  0  6]
  [11 11  2  0  2]
  [ 7  7  2  1  2]]

 ...

 [[ 7  7  2  1  2]
  [12 12  1  0  8]
  [11 11  1  0  0]
  [11 11  2  0  2]
  [11 11  2  0  2]]

 [[13 15  4  0  0]
  [10  8  1  0 10]
  [11 11  1  0  0]
  [13 13  2  0  2]
  [13 13  2  0  2]]

 [[12 12  1  0  8]
  [15 14  2  0  4]
  [11 11  1  0  0]
  [13 13  2  0  2]
  [14 13  4  0  0]]] [array([[14, 14, 11, 11, 14]

## Summary

So this is how you can train a linear regression model for the task of students grade prediction with machine learning using Python.